name: video_editor_example
description: The example project for the video_editor package.
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.4.3

dependencies:
  flutter:
    sdk: flutter
  video_editor_2:
    path: ../
  fraction: ^5.0.3
  image_picker: ^1.1.2
  video_player: ^2.9.1
  path_provider: ^2.1.4
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
